### ISSUE TITLE
routing/http/server: limit response sizes

### ISSUE THREAD

**Issue by guseggert** [ipfs/go-libipfs#15]
Complementary to https://github.com/ipfs/go-libipfs/pull/9

By default we should limit response sizes of the server to whatever the client can accept by default (which is current 1 MiB).

**Comment by ethanbanez** [comment]
hi @guseggert I'm new to contributing. I saw the recommendation in #9 to use the standard libraries provided functionality for the server but I'm confused at where the default server option should be implemented. Should it be in the handler?

**Comment by BigLep** [comment]
@guseggert : can you provide pointers here please?

**Comment by lidel** [comment]
It feels important to have this, towards productizing [`Gateway.ExposeRoutingAPI`](https://github.com/ipfs/kubo/blob/master/docs/config.md#gatewayexposeroutingapi) in Kubo 0.24+.

The `routing/http/server` library could have configuration for setting `/routing/v1` response limits:
- max number of results 
- max byte budget  (max number of body bytes across responses -- i think we already have this since #9)
- max time budget  for responding per request (total) 

@hacdias thoughts on making the above configurable and exposing in Kubo in `Routing.DelegatedServer` (I think we want to make it a map with related flags, similar to [`RelayService`](https://github.com/ipfs/kubo/blob/master/docs/config.md#swarmrelayservice))?

**Comment by hacdias** [comment]
@lidel I think it is a good idea to let this options be configurable in Kubo. However, I don't need any additional changes need to be made to Boxo. Let's see:

1. **Max number of results**: already possible via `server.WithRecordsLimit` and `server.WithStreamingRecordsLimit`.
2. **Max byte budget**: the PR you link is for `client`. I don't understand how that would be useful for `server`.
3. **Max time budget per request**: server implementers provide a [`server.ContentRouter`](https://github.com/ipfs/boxo/blob/main/routing/http/server/server.go#L54-L74) implementation. They can define their timeouts there, no need to add more options to Boxo, unless we want some default IMHO.

What do you think?

**Comment by lidel** [comment]
(1) and (3) sgtm, for (2) I think the problem is real for server too:  someone could publish malicious provider or peer records and then ask routing  server to resolve and return them and response could  have very long multiaddrs or additional metadata in binary blobs returned for specific protocol (that could act as DoS vector )

**Comment by hacdias** [comment]
@lidel still regarding 2: shouldn't that be included in the implementation of `server.ContentRouter` itself?

**Comment by lidel** [comment]
We've discussed this today, and there nothing left to do on the boxo:

-  in case of [someguy](https://github.com/ipfs-shipyard/someguy) or kubo, we have middleware-proxy type of situation, so limit will be applied on the "client" side
- additional timeouts and limits can be set on reverse proxy like nginx
