### ISSUE TITLE
routing/http: Why wrap `Multiaddr` when original type implements `json.Unmarshaller`

### ISSUE THREAD

**Issue by masih** [ipfs/go-libipfs#38]
This repo [wraps](https://github.com/ipfs/go-libipfs/blob/c444cbbff6dd8e2ec1eaec0e18fa71baf52d3718/routing/http/types/ipfs.go#L30) `multiaddr.Multiaddr` around a struct to implement JSON unmarshalling. I am curious what is the rationale for this considering the original type indeed [implements](https://github.com/ipfs/go-libipfs/blob/c444cbbff6dd8e2ec1eaec0e18fa71baf52d3718/routing/http/types/ipfs.go#L30) `json.Unmarshaller`.

**Comment by guseggert** [comment]
This is required because we can't unmarshal to an interface, it must be a concrete type, and [the concrete type for multiaddrs is not exported](https://github.com/multiformats/go-multiaddr/blob/f317559337171436148d927749f783f33b82a698/multiaddr.go#L12)!  This is unfortunate but is the best we can do until this is fixed in `go-multiaddr`.

**Comment by masih** [comment]
sigh; thank you
