### ISSUE TITLE
Blockstore#AllKeysChan not returning all cids in the set

### ISSUE THREAD

**Issue by pkieltyka** [ipfs/go-libipfs#566]
boxo version: 0.17.0

I have a custom pinning service using ipfs-lite and I've been prototyping with boxo to see how the service feels. I've pinned some content, and setup a gateway and all is working well.

However, when I get the channel from blockService.blockStore.AllKeysChan, and then traverse it to print all CIDs in the blockStore, its in fact not returning all keys. I'm only seeing CIDv1 hashes being returned.

When I try blockStore.Has(ctx, cid), then it works correctly for both CIDv0 and CIDv1 hashes, so its strange the AllKeysChan wouldn't return the complete set.

**Comment by aschmahmann** [comment]
@pkieltyka are you sure it's not actually returning all the keys in the set? Likely you're just having all your CIDv0s converted to CIDv1s with a raw codec as described in the interface documentation https://github.com/ipfs/boxo/blob/0536783b09d58f016aefe238091981f397c31278/blockstore/blockstore.go#L51-L59.

---

Some notes in case you're curious:
1. CIDv0s are convertible into CIDv1s. In particular, the binary encoding of a CIDv0 is sha2-256-256 multihash (where the dag-pb codec is implied) and the CIDv1 equivalent encoding would have the CIDv1 identifier (0x01) followed by the dag-pb codec prefixing the sha2-256-256 multihash.
  - See https://cid.ipfs.tech/#QmdmQXB2mzChmMeKY47C43LxUdg1NDJ5MWcKMKxDu7RgQm and https://cid.ipfs.tech/#bafybeihfg3d7rdltd43u3tfvncx7n5loqofbsobojcadtmokrljfthuc7y as an example comparison, but checking out the specs and playing around with cid.ipfs.tech should help you explore here
2. Most blockstores intentionally key based on multihash rather than CID because the way a block is validated is using it's (multi)hash.
   - This means whether data is accessed using either the CIDv0 or CIDv1 form it accesses the same data (and it's stored only once).
   - Similarly whether the data is accessed using say a `raw` codec (could apply to any data) or something more specific like dag-pb, dag-cbor, or cbor the same data is returned (and can be stored only once).

While for many cases the return API here could also have been multihashes, for a combination of historical reasons (and ease of upgrading to support CIDv1) as well practical ones (people tend to work with and print out CIDs more frequently, and some users might want to expose codec and CID version information) it hasn't been changed.

**Comment by pkieltyka** [comment]
thank you @aschmahmann very much for your thorough and helpful response. Indeed the full set is present and CIDs were being converted from CIDv0 to CIDv1.

I'm basing my original prototype on ipfs-lite. I agree its better to "key" based on multihash rather then CID. Any suggestions on how to do this..? See https://github.com/hsanjuan/ipfs-lite/blob/master/ipfs.go#L131

ipfs-lite and the "litepeer" example uses an in-memory data store (https://github.com/hsanjuan/ipfs-lite/blob/master/examples/litepeer/litepeer.go#L21) -- so perhaps this has something to do with it..? I tried to use the go-ds-pebble datastore, and same issue. 

it's not clear and pretty confusing what is going on with these multihashes / conversion. I'm not sure where the auto-conversion is happening and as I read the boxo source, the blockstore implementation (which is what I'm using), looks like it should support multihashes with `cid.Cid` which keeps track of the version/type and can return the multihash (thats also my understanding from reading the source).

**Comment by aschmahmann** [comment]
If your Blockstore is created by the function in boxo that creates one from a backing datastore (which is most uses of the Blockstore interface including the one you linked in ipfs-lite), then you're all set and internally it already keys on multihash https://github.com/ipfs/boxo/blob/0536783b09d58f016aefe238091981f397c31278/blockstore/blockstore.go#L146.

In general you shouldn't need to worry too much about the implementation details here unless there's a strong need. The boxo defaults should be fine, and in general just following the rules and docs from the interface should be sufficient.

A reasonable way to think about the boxo default blockstore implementation is:
1. Are you trying to do a put/lookup based on a CID (e.g. Put/Get/Has/Delete) -> the underlying implementation will extract the multihash and use that
2. Are you returning a CID -> return a CID format that conveys enough useful information (e.g. when Get returns a Block object that has a CID just use the CID that got passed since you have it, for AllKeysChan just use a raw CIDv1 because it's the simplest and most uniform way to do so

Going to close this since GitHub issues aren't particularly good for having discussions. Forums like https://discuss.ipfs.tech/ are better at that. Feel free to link to here (and post a link from here to there) if you've got more questions though.

**Comment by pkieltyka** [comment]
thank you -- will do.

I'll do some more introspection, but, it is strange that AllKeysChan is converting these hashes at the time of providing the information. If I ever try to use that as a cursor to the index of data, it's unreliable of course. I'll check the data/blocks directly inside of the datastore instead, and perhaps write my own adapter if I have to. Hopefully indeed its being stored as multihashes correctly, I'll confirm to make sure because yes I wouldn't want to be storing the data twice or adding extra unnecessary overhead. 

Finally, I'll say that boxo has been really cool to work with, and the overall stack is highly modular. I understand its been evolving for over a decade, and its a large codebase so its not easy to achieve a perfect system, but I do feel its settling and stabilizing, and excited for the new improvements to Amino which I assume we'll see in boxo and the overall system will get even more efficient and capable.

thanks for all you + your teams work.
